export const mockSongs = [
  {
    id: "1",
    title: "Blinding Lights",
    artist: "The Weeknd",
    album: "After Hours",
    genre: "Pop/R&B",
    albumCover: "/placeholder.svg?height=500&width=500",
    previewUrl: "https://example.com/preview/1",
  },
  {
    id: "2",
    title: "Bad Guy",
    artist: "Billie Eilish",
    album: "When We All Fall Asleep, Where Do We Go?",
    genre: "Pop",
    albumCover: "/placeholder.svg?height=500&width=500",
    previewUrl: "https://example.com/preview/2",
  },
  {
    id: "3",
    title: "Levitating",
    artist: "Dua Lipa",
    album: "Future Nostalgia",
    genre: "Pop/Disco",
    albumCover: "/placeholder.svg?height=500&width=500",
    previewUrl: "https://example.com/preview/3",
  },
  {
    id: "4",
    title: "Savage Love",
    artist: "Jason Derulo",
    album: "Savage Love",
    genre: "Pop",
    albumCover: "/placeholder.svg?height=500&width=500",
    previewUrl: "https://example.com/preview/4",
  },
  {
    id: "5",
    title: "Watermelon Sugar",
    artist: "Harry Styles",
    album: "Fine Line",
    genre: "Pop/Rock",
    albumCover: "/placeholder.svg?height=500&width=500",
    previewUrl: "https://example.com/preview/5",
  },
  {
    id: "6",
    title: "Dynamite",
    artist: "BTS",
    album: "BE",
    genre: "K-Pop",
    albumCover: "/placeholder.svg?height=500&width=500",
    previewUrl: "https://example.com/preview/6",
  },
  {
    id: "7",
    title: "Mood",
    artist: "24kGoldn ft. iann dior",
    album: "El Dorado",
    genre: "Hip-Hop/Pop",
    albumCover: "/placeholder.svg?height=500&width=500",
    previewUrl: "https://example.com/preview/7",
  },
  {
    id: "8",
    title: "Positions",
    artist: "Ariana Grande",
    album: "Positions",
    genre: "Pop/R&B",
    albumCover: "/placeholder.svg?height=500&width=500",
    previewUrl: "https://example.com/preview/8",
  },
  {
    id: "9",
    title: "Therefore I Am",
    artist: "Billie Eilish",
    album: "Happier Than Ever",
    genre: "Pop",
    albumCover: "/placeholder.svg?height=500&width=500",
    previewUrl: "https://example.com/preview/9",
  },
  {
    id: "10",
    title: "Kings & Queens",
    artist: "Ava Max",
    album: "Heaven & Hell",
    genre: "Pop",
    albumCover: "/placeholder.svg?height=500&width=500",
    previewUrl: "https://example.com/preview/10",
  },
  {
    id: "11",
    title: "Midnight Sky",
    artist: "Miley Cyrus",
    album: "Plastic Hearts",
    genre: "Pop/Rock",
    albumCover: "/placeholder.svg?height=500&width=500",
    previewUrl: "https://example.com/preview/11",
  },
  {
    id: "12",
    title: "Lonely",
    artist: "Justin Bieber & benny blanco",
    album: "Justice",
    genre: "Pop",
    albumCover: "/placeholder.svg?height=500&width=500",
    previewUrl: "https://example.com/preview/12",
  },
];
